main:
  - identifier: blog
    name: 文章
    pageRef: /blog
    weight: 1
  - identifier: docs
    name: 文档
    pageRef: /docs
    weight: 2
  - name: GitHub
    url: https://github.com/
    weight: 3
    params:
      icon: github
  - name: 主题
    weight: 4
    params:
      type: theme-toggle

sidebar:
  - identifier: docs
    name: 文档
    pageRef: /docs
    weight: 1
  - identifier: hugo-docs
    name: Hugo 文档
    url: https://gohugo.io/documentation/
    weight: 2
